---
- name: Install HTTP servers
  hosts: n2
  become: yes

  tasks:  
  - name: Install httpd
    yum:
      name: httpd
      state: present

  - name: Start and enable Apache service
    service:
      name: httpd
      state: started
      enabled: yes
...
