---
- name: Install HTTP servers
  hosts: n1
  become: yes

  tasks:  
  - name: Install Apache2
    yum:
      name: apache2
      state: present

  - name: Start and enable apache2 service
    service:
      name: apache2
      state: started
      enabled: yes
...
